program PdvTex;

uses
  Forms,
  Principal_00 in 'Principal_00.pas' {Principal},
  Produtos_00 in 'Produtos_00.pas' {Produtos00},
  Produtos_01 in 'Produtos_01.pas' {Produtos01},
  Produtos_02 in 'Produtos_02.pas' {Produtos02},
  Conexao_BD in 'Conexao_BD.pas' {ConexaoBD: TDataModule},
  Grupos_00 in 'Grupos_00.pas' {Grupos00},
  Grupos_01 in 'Grupos_01.pas' {Grupos01},
  Grupos_02 in 'Grupos_02.pas' {Grupos02},
  Fornecedores_00 in 'Fornecedores_00.pas' {Fornecedores00},
  Fornecedores_01 in 'Fornecedores_01.pas' {Fornecedores01},
  Fornecedores_02 in 'Fornecedores_02.pas' {Fornecedores02},
  Rotinas_Gerais in 'Rotinas_Gerais.pas',
  Sobre_00 in 'Sobre_00.pas' {Sobre00},
  Frente_Loja_00 in 'Frente_Loja_00.pas' {Frente_Loja00},
  Mvto_Compra_00 in 'Mvto_Compra_00.pas' {Mvto_Compra00},
  Cancela_Cupons_00 in 'Cancela_Cupons_00.pas' {Cancela_Cupons00},
  Caixa_Abertura_00 in 'Caixa_Abertura_00.pas' {Caixa_Abertura00},
  Caixa_Fechamento_00 in 'Caixa_Fechamento_00.pas' {Caixa_Fechamento00},
  Caixa_Sangria_00 in 'Caixa_Sangria_00.pas' {Caixa_Sangria00},
  Caixa_Deposito_00 in 'Caixa_Deposito_00.pas' {Caixa_Deposito00},
  Usuario_00 in 'Usuario_00.pas' {Usuario00},
  Usuario_01 in 'Usuario_01.pas' {Usuario01},
  Usuario_02 in 'Usuario_02.pas' {Usuario02},
  Login_00 in 'Login_00.pas' {Login00},
  Rel_RegistroCaixa_00 in 'Rel_RegistroCaixa_00.pas' {Rel_RegistroCaixa00},
  Rel_RegistroCaixa_01 in 'Rel_RegistroCaixa_01.pas' {Rel_RegistroCaixa01},
  Fechamento_Cupom_00 in 'Fechamento_Cupom_00.pas' {Fechamento_Cupom00},
  Cancela_Cupons_Login_00 in 'Cancela_Cupons_Login_00.pas' {Cancela_Cupons_Login00},
  Informacao_Maquinas_00 in 'Informacao_Maquinas_00.pas' {Informacao_Maquinas00},
  Informacao_Maquinas_01 in 'Informacao_Maquinas_01.pas' {Informacao_Maquinas01},
  Informacao_Maquinas_02 in 'Informacao_Maquinas_02.pas' {Informacao_Maquinas02},
  Conexao_00 in 'Conexao_00.pas' {Conexao00},
  Abertura_Caixa_F9 in 'Abertura_Caixa_F9.pas' {Abertura_CaixaF9},
  Permissoes_00 in 'Permissoes_00.pas' {Permissoes00},
  Estoque_00 in 'Estoque_00.pas' {Estoque00},
  Estoque_01 in 'Estoque_01.pas' {Estoque01},
  Limpeza_00 in 'Limpeza_00.pas' {Limpeza00},
  Limpeza_Login_00 in 'Limpeza_Login_00.pas' {Limpeza_Login00},
  Rel_Fechamento_Caixa_00 in 'Rel_Fechamento_Caixa_00.pas' {RelFechamentoCaixa00},
  Rel_Lucratividade_00 in 'Rel_Lucratividade_00.pas' {RelLucratividade00},
  Rel_Lucratividade_01 in 'Rel_Lucratividade_01.pas' {RelLucratividade01},
  Apaga_Item_00 in 'Apaga_Item_00.pas' {ApagaItem00},
  Caixa_Sangria_02 in 'Caixa_Sangria_02.pas' {Caixa_Sangria02},
  Caixa_Sangria_03 in 'Caixa_Sangria_03.pas' {Caixa_Sangria03},
  Caixa_Sangria_01 in 'Caixa_Sangria_01.pas' {Caixa_Sangria01},
  Caixa_Sangria_Login_00 in 'Caixa_Sangria_Login_00.pas' {Caixa_Sangria_Login00},
  Rel_Lucratividade_02 in 'Rel_Lucratividade_02.pas' {RelLucratividade02},
  Valor_Venda_Diaria_00 in 'Valor_Venda_Diaria_00.pas' {ValorVendaDiaria00},
  Rel_Fornecedor_Ultima_Venda_00 in 'Rel_Fornecedor_Ultima_Venda_00.pas' {RelFornecedorUltimaVenda00},
  Rel_Fornecedor_Ultima_Venda_01 in 'Rel_Fornecedor_Ultima_Venda_01.pas' {RelFornecedorUltimaVenda01},
  Rel_Lucratividade_03 in 'Rel_Lucratividade_03.pas' {RelLucratividade03},
  Posicao_Atual_Estoque_00 in 'Posicao_Atual_Estoque_00.pas' {PosicaoAtualEstoque00},
  Posicao_Atual_Estoque_01 in 'Posicao_Atual_Estoque_01.pas' {PosicaoAtualEstoque01},
  Entrada_Produtos_NF_00 in 'Entrada_Produtos_NF_00.pas' {EntradaProdutosNF00},
  Cancela_Item_Login_00 in 'Cancela_Item_Login_00.pas' {CancelaItemLogin00},
  Rel_Item_Apagado_Venda_00 in 'Rel_Item_Apagado_Venda_00.pas' {RelItemApagadoVenda00},
  Rel_Item_Apagado_Venda_01 in 'Rel_Item_Apagado_Venda_01.pas' {RelItemApagadoVenda01},
  Cancela_Entrada_00 in 'Cancela_Entrada_00.pas' {CancelaEntrada00},
  Historico_Nota_Entrada_00 in 'Historico_Nota_Entrada_00.pas' {HistoricoNotaEntrada00},
  Historico_Nota_Entrada_01 in 'Historico_Nota_Entrada_01.pas' {HistoricoNotaEntrada01},
  Registra_PDVTEX in 'Registra_PDVTEX.pas' {RegistraPDVTEX},
  Empresa_00 in 'Empresa_00.pas' {Empresa00},
  Splash_Screen in 'Splash_Screen.pas' {SplashScreen},
  Splash_Screen_Fechamento in 'Splash_Screen_Fechamento.pas' {SplashScreenFechamento},
  Clientes_00 in 'Clientes_00.pas' {Clientes00},
  Clientes_01 in 'Clientes_01.pas' {Clientes01},
  Clientes_02 in 'Clientes_02.pas' {Clientes02},
  MSG_Adiciona_Cliente_Pedido in 'MSG_Adiciona_Cliente_Pedido.pas' {MSGAdicionaClientePedido},
  Rel_ComprasClientes_00 in 'Rel_ComprasClientes_00.pas' {Rel_ComprasClientes00},
  Rel_ComprasClientes_01 in 'Rel_ComprasClientes_01.pas' {Rel_ComprasClientes01},
  Rel_Estoque_Minimo_00 in 'Rel_Estoque_Minimo_00.pas' {RelEstoqueMinimo00},
  Rel_Estoque_Minimo_01 in 'Rel_Estoque_Minimo_01.pas' {RelEstoqueMinimo01},
  Trocas_00 in 'Trocas_00.pas' {Trocas00},
  Trocas_01 in 'Trocas_01.pas' {Trocas01},
  Trocas_02 in 'Trocas_02.pas' {Trocas02},
  Trocas_03 in 'Trocas_03.pas' {Trocas03},
  Rel_ComprasClientes_02 in 'Rel_ComprasClientes_02.pas' {Rel_ComprasClientes02},
  Rel_ComprasClientes_03 in 'Rel_ComprasClientes_03.pas' {Rel_ComprasClientes03},
  Inventario_00 in 'Inventario_00.pas' {Inventario00},
  Inventario_01 in 'Inventario_01.pas' {Inventario01},
  Contagem_Cedulas_00 in 'Contagem_Cedulas_00.pas' {ContagemCedulas00},
  Atualizacao_00 in 'Atualizacao_00.pas' {Atualizacao00},
  Notas_Fiscais_00 in 'Notas_Fiscais_00.pas' {NotasFiscais00},
  Notas_Fiscais_01 in 'Notas_Fiscais_01.pas' {NotasFiscais01},
  Notas_Fiscais_02 in 'Notas_Fiscais_02.pas' {NotasFiscais02},
  Rel_Lucratividade_D00 in 'Rel_Lucratividade_D00.pas' {RelLucratividadeD00},
  Rel_Lucratividade_D01 in 'Rel_Lucratividade_D01.pas' {RelLucratividadeD01},
  Rel_Lucratividade_D02 in 'Rel_Lucratividade_D02.pas' {RelLucratividadeD02},
  Rel_Lucratividade_D03 in 'Rel_Lucratividade_D03.pas' {RelLucratividadeD03},
  Rel_Perda_Produtos_00 in 'Rel_Perda_produtos_00.pas' {RelPerdaProdutos00},
  EnviarEstoque_00 in 'EnviarEstoque_00.pas' {EnviarEstoque00},
  Rel_Cupom_Fiscal_00 in 'Rel_Cupom_Fiscal_00.pas' {RelCupomFiscal00},
  DelphiZXingQRCode in 'DelphiZXIngQRCode.pas';

{$R *.res}

begin
  //*** Ampulheta do Cursor ***
  Ampulheta();

  //*** Inicializa a Aplicação ***
  Application.Initialize;
  Application.CreateForm(TConexaoBD, ConexaoBD);
  Application.CreateForm(TLogin00, Login00);
  Application.CreateForm(TPrincipal, Principal);
  Application.Run;
end.
